name: Test and publish

on: [push, pull_request, workflow_dispatch]

env:
  REPOSITORY: moodle-bench-diff
  DOCKERHUB_OWNER: moodlehq
  GH_OWNER: moodlehq

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build . -t moodle-bench-diff

  Publish:
    # Completely avoid forks and pull requests to try this job.
    if: github.repository_owner == 'moodlehq' && contains(fromJson('["push", "workflow_dispatch"]'), github.event_name)
    # Requires Test to pass
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Calculate the tags to be pussed to the registries.
      - name: Calculate image tag names
        id: calculatetags
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_OWNER }}/${{ env.REPOSITORY }}
            ghcr.io/${{ env.GH_OWNER }}/${{ env.REPOSITORY }}
          tags: |
            type=raw,value=latest

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push to Docker Hub and Github registries
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.calculatetags.outputs.tags }}

      # https://github.com/peter-evans/dockerhub-description
      # Note that we only update the description with the master branch version.
      - name: Set Docker Hub description from README.md
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_OWNER }}/${{ env.REPOSITORY }}
